### ISSUE TITLE
Can i host the service on my own vps?

### ISSUE THREAD

**Issue by ASUSWA** [Frizz925/gbf-proxy#2]
If it is possible ,how to do it?Thanks for your works.

**Comment by frizz925** [comment]
I'll write up the setup instructions this weekend

**Comment by ASUSWA** [comment]
Thank you very much!

**Comment by frizz925** [comment]
I'll just write a quick and dirty guide here before writing a proper one on the readme. This leverages the *local mode* of the program, which is the quick and easy way of running all the services using a single command. This was meant to be used locally on your own computer or for development purposes, however. You still can tweak it a little bit so it can run on a server and accept all connections.

1. Download the binary file from the [release page](https://github.com/Frizz925/gbf-proxy/releases)
```
wget https://github.com/Frizz925/gbf-proxy/releases/download/v0.1.0/gbf-proxy-linux-amd64 -O gbf-proxy
```
2. Start the proxy in *local mode* which listens on port **8088** on **all interfaces**
```
./gbf-proxy local --host 0.0.0.0 --port 8088
```

**Comment by ASUSWA** [comment]
> I'll just write a quick and dirty guide here before writing a proper one on the readme. This leverages the _local mode_ of the program, which is the quick and easy way of running all the services using a single command. This was meant to be used locally on your own computer or for development purposes, however. You still can tweak it a little bit so it can run on a server and accept all connections.
> 
> 1. Download the binary file from the [release page](https://github.com/Frizz925/gbf-proxy/releases)
> 
> ```
> wget https://github.com/Frizz925/gbf-proxy/releases/download/v0.1.0/gbf-proxy-linux-amd64 -O gbf-proxy
> ```
> 1. Start the proxy in _local mode_ which listens on port **8088** on **all interfaces**
> 
> ```
> ./gbf-proxy local --host 0.0.0.0 --port 8088
> ```
I have try it on my server,but when i tried the second command it just showed:
 `-bash: ./gbf-proxy: Permission denied`
I use the vultr server runs debian9,no firewall group and i am root of course.
Thanks for your work again.

**Comment by frizz925** [comment]
Execute permission perhaps? Run `chmod +x gbf-proxy` and try again.

**Comment by ASUSWA** [comment]
Now runs well thanks.
