### ISSUE TITLE
Question for Installation

### ISSUE THREAD

**Issue by neahyun** [Frizz925/gbf-proxy#8]
Do I need to download the file and run something?
The only thing I did was just installed SwitchyOmega and followed your chrome setup instruction.
But I don't feel any change in the game, and I can't find the game asset cached in my desktop.
Do i misunderstand something?
I'm sorry if I'm making dumb question, please understand that I have no knowledge about technology.
Thank you.

**Comment by frizz925** [comment]
It caches the game assets on the server, not your PC.
